# SPDX-FileCopyrightText: Copyright (c) 2022-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.24.0
ec2:
  type: t2.2xlarge
assets:
  npmrc: yegor256/objectionary-secrets#npmrc
install: |
  pip install git+https://chromium.googlesource.com/external/gyp
  npm install --no-color
  npm install --no-color mocha
  pdd -f /dev/null -v
release:
  pre: false
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i "s/0\.0\.0/${tag}/" package.json
    sed -i "s/0\.0\.0/${tag}/" src/version.js
    sed -i "s/0000-00-00/$(date +%Y-%m-%d)/" src/version.js
    npx grunt --no-color
    git commit -am "set version to ${tag}"
    chmod 600 ../npmrc
    npm publish --no-color --userconfig=../npmrc
merge:
  script: |-
    npx grunt --no-color
